### ISSUE TITLE
MaxBbangCount와 BbangCount에 관한 고찰

### ISSUE THREAD

**Issue by armsterd** [doughnutdough5/BangBangBang#21]
1. BbangCount =  0 이어야 쏴진다.
2. BbangCount = 1 이 되면 안쏴진다.
3. 그래서 MaxBbangCount를 따로 설정하여 양의 방향으로 커지게 만들면, 무기와 캐릭터 특성을 고려하여 인게임에서 빵야 횟수를 컨트롤 할 수 있을 것이다.

**Comment by Freak-J** [comment]
1. bbangCount는 음의 방향으로 설정이 되며, 0을 향해 올라갑니다.
2. bbangCount = 1이 되면 안쏴지는 것은 맞습니다.
3. 그러므로 MaxBbangCount를 음수로 설정해야 합니다. (예시로 -4로 설정하면 빵야를 5번 쏠 수 있습니다)
다음 페이즈로 전환시 MaxBbangCount를 해당 캐릭터의 BbangCount 로 설정하면 될 것 같습니다.

**Comment by armsterd** [comment]
----- [기존 코드] ----
user.class.js
```
  canUseBbang() {
    return this.characterData.bbangCount < this.maxBbangCount;
  }

```
  ```
setBbangCount(count) {
    this.maxBbangCount = count;
  }

```

bbangCardHandler.js
```
  if (cardUsingUser.canUseBbang()) {
    // 빵야 실패
    const errorResponse = {
      useCardResponse: {
        success: false,
        failCode: Packets.GlobalFailCode.ALREADY_USED_BBANG,
      },
    };
    return errorResponse;
  }
```
위의 canUseBbang 함수를 사용한 if 조건문이 true로 날라오면, 빵야 카드를 사용할 수 있다는 의미지만, if 실행문쪽은 실패 로직으로 구성되어 있습니다. 또한, bbangCardHandler에서 canUseBbang을 검사하면 테스트 상황 시 빵야는 사용되지 않지만 정작 카드는 사라지는 오류가 있습니다.
따라서 아래와 같이 변경할 것을 제안합니다.

1. canUseBbang 로직 변경
2. setBbangCount 명칭 변경
3. if 조건문 변경 및 위치 변경 (bbangCardHandler.js -> useCard.handler.js)

---- [변경 제안 코드] ----
user.class.js
```
  canUseBbang() {
    return (
      0 >= this.characterData.bbangCount && this.characterData.bbangCount >= this.maxBbangCount
    );
  }

  setMaxBbangCount(count) {
    this.maxBbangCount = count;
  }

```
bbangCardHandler.js -> useCard.handler.js
```
  if (!cardUsingUser.canUseBbang()) {
    // 빵야 실패
    const errorResponse = {
      useCardResponse: {
        success: false,
        failCode: Packets.GlobalFailCode.ALREADY_USED_BBANG,
     },
    };
    return errorResponse;
 }
```

**Comment by doughnutdough5** [comment]
전 좋은 것 같습니다.
수정 후 PR 올려주시면 회의시간에 다 같이 코드 리뷰 후 머지하겠습니다

**Comment by doughnutdough5** [comment]
적용 완료
