### ISSUE TITLE
CI/CD 구축 내용

### ISSUE THREAD

**Issue by bigsmile1460** [doughnutdough5/BangBangBang#48]
Jenkins 테스트 환경
- 물리 사양: t2.micro ( vCPU: 1, RAM: 1GiB)
- O/S: ubuntu 22.04 LTS

테스트 내용
- 깃허브 webhook과 jenkins를 연동하여 CI/CD 구축을 하려고 함.
-  jenkins를 통한 자동 배포 환경 구축 중 node.js 환경 및 빌드 경로 문제, 메모리 부족 현상 발견
    -> 빌드 스크립트 작성 중 경로 문제 발생 
    -> 경로 문제 해결을 위한 테스트 진행 중 node.js 환경이 jenkins가 실행하는 환경과 다름 발견
    -> nodejs 환경은 jenkins 설정을 통해 해결 가능

테스트 결과
- ec2 프리티어에서 jenkins 운용이 프리티어 자원에 비해 jenkins가 너무 무겁다고 판단되어 Docker를 이용하여 다시 구축하는 방향으로 전환하여 테스트 진행

**Comment by bigsmile1460** [comment]
Docker 테스트 환경
- 물리 사양: t2.micro ( vCPU: 1, RAM: 1GiB)
- O/S: ubuntu 22.04 LTS

테스트 내용
- 깃허브 actions과 Docker를 연동하여 CI/CD 구축을 하려고 함.
- 자동 배포 환경 구축 중 ec2에 ssh 연결이 안되는 문제에 봉착
`Run ssh -tt -o StrictHostKeyChecking=no *** << 'EOF'
Warning: Permanently added '54.169.251.157' (ED25519) to the list of known hosts.
***: Permission denied (publickey).
Error: Process completed with exit code 255.`
-> appleboy/ssh-action@master를 사용하여 해결
- 도커 컨테이너 종료되는 문제
-> 도커 run 명령어 옵션(detach) 추가 ex) docker run -d
-> 서버 pm2(fork)로 실행 ->background에서 실행되던 프로세스를 foreground로 변경 (pm2 start -> pm2-runtime start)
- 클라이언트 접속 안되는 문제 해결
-> 방화벽 확인
-> ec2 인바운드 규칙 확인
-> node, npm 버전 확인 -> 버전 업데이트 (16.x -> 20.x)
-> docker run 명령어 포트(포워딩) 옵션 추가
-> 서버 host 변경 

테스트 결과
- ec2에 CI/CD까지 구현 완료 ( git actions -> docker -> pm2 )

**Comment by doughnutdough5** [comment]
정말 많은 일이 있었죠..

**Comment by sdh02142** [comment]
변경하여 적용된 부분 잘 요약해주셔서 감사합니다!

**Comment by armsterd** [comment]
테스트는 오래걸렸지만 뜻깊은 경험!

**Comment by Freak-J** [comment]
킹 갓 도커 
좋은 경험이었습니다
